/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cz.nomi.cwg;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int chart=0x7f020000;
        public static final int copy=0x7f020001;
        public static final int down=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int up=0x7f020004;
    }
    public static final class id {
        public static final int button=0x7f070004;
        public static final int image=0x7f07000a;
        public static final int list=0x7f070005;
        public static final int listItemCount=0x7f070002;
        public static final int listItemTitle=0x7f070001;
        public static final int menuAddOther=0x7f070010;
        public static final int menuAddSame=0x7f07000f;
        public static final int menuAutoMerge=0x7f07001e;
        public static final int menuCopy=0x7f070013;
        public static final int menuDelete=0x7f070015;
        public static final int menuDuplicity=0x7f070016;
        public static final int menuEraseDb=0x7f07001f;
        public static final int menuExportCsv=0x7f07001b;
        public static final int menuExportText=0x7f07001a;
        public static final int menuImportCatalog=0x7f070017;
        public static final int menuImportCsv=0x7f070019;
        public static final int menuImportText=0x7f070018;
        public static final int menuMerge=0x7f070014;
        public static final int menuPreference=0x7f07001d;
        public static final int menuRemoveOne=0x7f070011;
        public static final int menuRename=0x7f070012;
        public static final int menuShow=0x7f07000e;
        public static final int menuStatistics=0x7f07001c;
        public static final int rename_title=0x7f070000;
        public static final int search=0x7f070003;
        public static final int show_catalog_id=0x7f070008;
        public static final int show_catalog_title=0x7f070007;
        public static final int show_count=0x7f070009;
        public static final int show_title=0x7f070006;
        public static final int stats_cwg_count=0x7f07000b;
        public static final int stats_cwg_duplicity=0x7f07000d;
        public static final int stats_cwg_unique=0x7f07000c;
    }
    public static final class layout {
        public static final int dialog_rename=0x7f030000;
        public static final int list_item=0x7f030001;
        public static final int main=0x7f030002;
        public static final int show=0x7f030003;
        public static final int stats=0x7f030004;
    }
    public static final class menu {
        public static final int context=0x7f060000;
        public static final int main=0x7f060001;
    }
    public static final class string {
        public static final int add_other_version=0x7f050009;
        public static final int add_same=0x7f050008;
        public static final int app_name=0x7f050000;
        public static final int are_you_sure_clean_whole_db=0x7f05001f;
        public static final int are_you_sure_delete_cwg=0x7f05000e;
        public static final int auto_merge=0x7f05001b;
        public static final int auto_merging=0x7f05001c;
        public static final int catalog_id=0x7f050029;
        public static final int catalog_title=0x7f050028;
        public static final int copy=0x7f05000b;
        public static final int count=0x7f05002a;
        public static final int cwg_count=0x7f050021;
        public static final int decrement=0x7f050011;
        public static final int delete=0x7f05000c;
        public static final int delete_cwg=0x7f05000d;
        public static final int duplicate_cwg=0x7f050023;
        public static final int duplicity=0x7f050012;
        public static final int erase_database=0x7f05001e;
        public static final int erase_db=0x7f05001d;
        public static final int export=0x7f050014;
        public static final int export_csv=0x7f050019;
        public static final int export_text=0x7f050017;
        public static final int exporting=0x7f050025;
        public static final int image=0x7f05002b;
        public static final int import_=0x7f050013;
        public static final int import_catalog=0x7f050015;
        public static final int import_csv=0x7f050018;
        public static final int import_text=0x7f050016;
        public static final int importing=0x7f050024;
        public static final int main_activity=0x7f050001;
        public static final int merge=0x7f050010;
        public static final int please_wait=0x7f050026;
        public static final int pref_catalog_url=0x7f050005;
        public static final int pref_image_url=0x7f050006;
        public static final int preference=0x7f05001a;
        public static final int preference_activity=0x7f050002;
        public static final int remove_one=0x7f05000f;
        public static final int rename=0x7f05000a;
        public static final int show=0x7f050007;
        public static final int show_activity=0x7f050004;
        public static final int statistics=0x7f050020;
        public static final int statistics_activity=0x7f050003;
        public static final int title=0x7f050027;
        public static final int unique_cwg=0x7f050022;
    }
    public static final class xml {
        public static final int preference=0x7f040000;
    }
}
