/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cz.nomi.cwg;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int button=0x7f060004;
        public static final int list=0x7f060005;
        public static final int listItemCount=0x7f060002;
        public static final int listItemTitle=0x7f060000;
        public static final int listItemVersion=0x7f060001;
        public static final int menuAddOther=0x7f060007;
        public static final int menuAddSame=0x7f060006;
        public static final int menuCopy=0x7f060008;
        public static final int menuDuplicity=0x7f06000a;
        public static final int menuEraseDb=0x7f06000f;
        public static final int menuExportCsv=0x7f06000e;
        public static final int menuExportText=0x7f06000d;
        public static final int menuImportCsv=0x7f06000c;
        public static final int menuImportText=0x7f06000b;
        public static final int menuRemove=0x7f060009;
        public static final int search=0x7f060003;
    }
    public static final class layout {
        public static final int list_item=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int context=0x7f050000;
        public static final int main=0x7f050001;
    }
    public static final class string {
        public static final int add_other_version=0x7f040002;
        public static final int add_same=0x7f040001;
        public static final int app_name=0x7f040000;
        public static final int are_you_sure_clean_whole_db=0x7f040010;
        public static final int copy=0x7f040003;
        public static final int count=0x7f04000e;
        public static final int duplicity=0x7f040005;
        public static final int erase_database=0x7f04000f;
        public static final int erase_db=0x7f04000c;
        public static final int export=0x7f040007;
        public static final int export_csv=0x7f04000b;
        public static final int export_text=0x7f040009;
        public static final int import_=0x7f040006;
        public static final int import_csv=0x7f04000a;
        public static final int import_text=0x7f040008;
        public static final int remove=0x7f040004;
        public static final int version=0x7f04000d;
    }
}
